WIP

diff --git a/scripts/mksecrets b/scripts/mksecrets
--- a/scripts/mksecrets
+++ b/scripts/mksecrets
@@ -1,6 +1,24 @@
 #!/usr/bin/env bash
 set -eo pipefail
 
+cloud_domain="$1"
+if [[ "x$cloud_domain" == "x" ]]; then
+  printf "Cloud domain required! Exiting..."
+  exit 1
+fi
+
+network_ip_range_start="$2"
+if [[ "x$network_ip_range_start" == "x" ]]; then
+  printf "Network ip range start required! Exiting..."
+  exit 1
+fi
+
+network_ip_range_end="$3"
+if [[ "x$network_ip_range_end" == "x" ]]; then
+  printf "Network ip range end required! Exiting..."
+  exit 1
+fi
+
 ensure() {
   local path
 
@@ -152,7 +170,7 @@ EOF
 
 cat >"$ID_SECRETS/.env" <<EOF
 PIDGEON_CLOUD_SSL="1"
-PIDGEON_CLOUD_DOMAIN="TODO"
+PIDGEON_CLOUD_DOMAIN="$cloud_domain"
 PIDGEON_CLOUD_API_KEY="$(cat "$ID_SECRETS/api.key")"
 PIDGEON_CLOUD_ID="pidgeon-$ID"
 
@@ -161,8 +179,8 @@ PIDGEON_DB_USER="pidgeon"
 PIDGEON_DB_PASSWORD="$(cat "$ID_SECRETS/postgres-pidgeon.key")"
 PIDGEON_DB_NAME="pidgeon"
 
-PIDGEON_NETWORK_IP_RANGE_START="192.168.1.0"
-PIDGEON_NETWORK_IP_RANGE_END="192.168.1.255"
+PIDGEON_NETWORK_IP_RANGE_START="$network_ip_range_start"
+PIDGEON_NETWORK_IP_RANGE_END="$network_ip_range_end"
 EOF
 
 cat >"$ID_SECRETS/secrets.yaml" <<EOF
